### ISSUE TITLE
ZoomHelper with multiple fragment

### ISSUE THREAD

**Issue by gauravbansod-retailogy** [Aghajari/ZoomHelper#5]
When using zoom helper in activity with multiple fragment , when navigating to new fragment to same activity , it holds instance of previous fragments view , ZooomHelper.release() not working

**Comment by Aghajari** [comment]
Hi @gauravbansod-retailogy ,
check this :
https://github.com/Aghajari/ZoomHelper/issues/4#issuecomment-725887938

**Comment by MohitDholakia** [comment]
Hello I am facing this same issue I have also tried the suggested link above but in case of multiple fragments on the same activity it causes this issue

**Comment by Aghajari** [comment]
Hi @MohitDholakia ,
could you share your codes here? or attach a simple project..

**Comment by MohitDholakia** [comment]
@Aghajari I have used one main activity which contains four fragments and below is the sample code for Main activity

```
override fun dispatchTouchEvent(ev: MotionEvent?): Boolean {
        return ZoomHelper.getInstance().dispatchTouchEvent(
            ev!!,
            findViewById<FrameLayout>(R.id.aBottomNavigation_frame)
        ) || super.dispatchTouchEvent(ev)
    }
```
Here every time I switch fragments zoom view contains an old zoomable view so on zooming for first time in another fragment incorrect image will appear

**Comment by Aghajari** [comment]
Hi @MohitDholakia ,
As i said before, This should solve your issue : [#4 (comment)](https://github.com/Aghajari/ZoomHelper/issues/4#issuecomment-725887938)

**Comment by MohitDholakia** [comment]
@Aghajari please look at the above code in which I have done exactly the same still facing this issue
