### ISSUE TITLE
getting crash on zoomhelper class.

### ISSUE THREAD

**Issue by kiran-shrestha-retailogy** [Aghajari/ZoomHelper#6]
in ZoomHelper class -> line number 205 and 351 I am getting crashes.

I am using this on recyclerview and adding and removing it at view attach and detach.

on both the lines -> onPostDelay() is used and the View may have already been destroyed and there is no null check for view inside the postdelay function.

Can you please check the issue.

**Comment by Aghajari** [comment]
Hi @kiran-shrestha-retailogy 
You're right, i'll fix it as soon as it's possible..

**Comment by kiran-shrestha-retailogy** [comment]
Thanks a lot @Aghajari.

**Comment by Aghajari** [comment]
Hello again,
ZoomHelper `v1.0.2-alpha` will fix this issue as well.

Check it out, if the problem was still there, attach a simple project + full error log..

**Comment by kiran-shrestha-retailogy** [comment]
Thank you for the update.
It's a rare occurrence and don't appear in normal devices.
I will connect with you if there is still some problem after update.
